Repository LuccaSA/ux-prisme, pull requests merged in 2019-08, with the labels that each got.

#23 lf3.0.6
  package-lock.json
  package.json
Labels: enhancement

#19 [guidelines] callout
  applications/prisme/src/app/components/feedback/callouts/callouts.feature.ts
  applications/prisme/src/app/components/feedback/callouts/callouts.page.ts
  applications/prisme/src/guidelines/components/feedback/callouts/callouts.guidelines.md
  applications/prisme/src/guidelines/components/feedback/callouts/images/placeholder.png
Labels: documentation

#25 Feat.vocabulary
  applications/prisme/src/app/components/layout/templates/templates.feature.html
  applications/prisme/src/app/components/misc/functions/functions.feature.html
  applications/prisme/src/app/components/misc/mixins/mixins.feature.html
  applications/prisme/src/app/components/misc/utilities/utilities.feature.html
  applications/prisme/src/app/components/overlays/popovers/popovers.page.ts
  applications/prisme/src/app/principles/content/content.module.ts
  applications/prisme/src/app/principles/content/content.page.ts
  applications/prisme/src/app/principles/content/format/format.feature.html
  applications/prisme/src/app/principles/content/format/format.feature.ts
  applications/prisme/src/app/principles/content/format/format.module.ts
  applications/prisme/src/app/principles/content/format/format.page.ts
  applications/prisme/src/app/principles/content/format/index.ts
  applications/prisme/src/app/principles/content/vocabulary/vocabulary.feature.ts
  applications/prisme/src/app/principles/content/vocabulary/vocabulary.page.ts
  applications/prisme/src/app/ressources/applications/applications.feature.html
  applications/prisme/src/app/ressources/assets/assets.feature.html
  applications/prisme/src/app/ressources/colors/colors.feature.html
  applications/prisme/src/guidelines/principles/content/vocabulary/images/placeholder.png
  applications/prisme/src/guidelines/principles/content/vocabulary/vocabulary.guidelines.md
  documentation/scss/scss-docs.ts
  libraries/common/src/lib/feature/content/feature-content.component.html
  libraries/common/src/style/_app-logo.scss
  libraries/common/src/style/_markdown.scss
  libraries/common/src/style/main.scss
Labels: documentation

#26 Fix schematics
  .vscode/launch.json
  package-lock.json
  package.json
Labels: bug
