Repository LuccaSA/ux-prisme, pull requests merged in 2019-10, with the labels that each got.

#78 Feat/assets
  applications/prisme/src/app/ressources/identity-ressources/applications/logo.model.ts
  applications/prisme/src/app/ressources/identity-ressources/assets/assets.feature.html
  applications/prisme/src/app/ressources/identity-ressources/assets/assets.feature.ts
  applications/prisme/src/app/ressources/ressource.model.ts
  applications/prisme/src/environments/environment.prod.ts
  applications/prisme/src/environments/environment.ts
  documentation/scss/scss-docs.ts
  libraries/common/src/lib/asset/asset-src.directive.ts
  libraries/common/src/lib/asset/asset.model.ts
  libraries/common/src/lib/asset/asset.module.ts
  libraries/common/src/lib/asset/asset.service.ts
  libraries/common/src/lib/asset/index.ts
  libraries/common/src/lib/common.module.ts
  libraries/common/src/lib/feature/content/feature-content.component.html
  libraries/common/src/lib/index.ts
  libraries/common/src/lib/markdown/index.ts
  libraries/common/src/lib/markdown/markdown-src.directive.ts
  libraries/common/src/lib/markdown/markdown.module.ts
  libraries/common/src/lib/tool/tool.component.html
  libraries/common/src/lib/tool/tool.model.ts
  libraries/common/src/lib/tool/tool.module.ts
  package-lock.json
  package.json
Labels: enhancement

#54 ajout /components/form/formly
  applications/prisme/src/app/components/form/form.module.ts
  applications/prisme/src/app/components/form/form.page.ts
  applications/prisme/src/app/components/form/formly/basic/basic.example.html
  applications/prisme/src/app/components/form/formly/basic/basic.example.ts
  applications/prisme/src/app/components/form/formly/formly.feature.html
  applications/prisme/src/app/components/form/formly/formly.feature.ts
  applications/prisme/src/app/components/form/formly/formly.module.ts
  applications/prisme/src/app/components/form/formly/formly.page.ts
  applications/prisme/src/app/components/form/formly/framed/framed.example.html
  applications/prisme/src/app/components/form/formly/framed/framed.example.ts
  applications/prisme/src/app/components/form/formly/index.ts
  applications/prisme/src/app/components/form/formly/supported/supported.example.html
  applications/prisme/src/app/components/form/formly/supported/supported.example.ts
  applications/prisme/src/app/components/form/index.ts
  applications/prisme/src/styles.scss
Labels: enhancement

#75 use LF 3.2
  applications/prisme/src/app/components/text/icons/basic/basic.example.html
  applications/prisme/src/app/components/text/icons/basic/basic.example.ts
  applications/prisme/src/app/components/text/icons/icons.feature.ts
  package-lock.json
  package.json
Labels: dependencies, enhancement

#76 [add] Theming Documentation
  applications/prisme/src/app/components/index.ts
  applications/prisme/src/app/components/misc/misc.module.ts
  applications/prisme/src/app/components/misc/misc.page.ts
  applications/prisme/src/app/components/misc/theming/index.ts
  applications/prisme/src/app/components/misc/theming/theming.feature.html
  applications/prisme/src/app/components/misc/theming/theming.feature.ts
  applications/prisme/src/app/components/misc/theming/theming.module.ts
  applications/prisme/src/app/components/misc/theming/theming.page.ts
  applications/prisme/src/app/components/misc/theming/theming.style.scss
  applications/prisme/src/guidelines/components/misc/theming/theming.guidelines.md
  documentation/scss/scss-docs.ts
  libraries/common/src/lib/documentation/theme/theme.component.html
  libraries/common/src/lib/documentation/theme/theme.component.scss
  libraries/common/src/lib/documentation/theme/theme.component.ts
  libraries/common/src/lib/documentation/theme/theme.module.ts
  libraries/common/src/style/_markdown.scss
  tools/scss-docs.js
Labels: documentation, enhancement

#77 call prisme proxy with https
  applications/prisme/src/environments/environment.prod.ts
  applications/prisme/src/environments/environment.ts
Labels: enhancement

#90 [doc] [add] Error Page
  applications/prisme/src/app/components/feedback/error-page/basic/basic.example.html
  applications/prisme/src/app/components/feedback/error-page/basic/basic.example.scss
  applications/prisme/src/app/components/feedback/error-page/basic/basic.example.ts
  applications/prisme/src/app/components/feedback/error-page/error-page.feature.html
  applications/prisme/src/app/components/feedback/error-page/error-page.feature.ts
  applications/prisme/src/app/components/feedback/error-page/error-page.module.ts
  applications/prisme/src/app/components/feedback/error-page/error-page.page.ts
  applications/prisme/src/app/components/feedback/error-page/index.ts
  applications/prisme/src/app/components/feedback/feedback.module.ts
  applications/prisme/src/app/components/feedback/feedback.page.ts
  applications/prisme/src/app/components/index.ts
  applications/prisme/src/guidelines/components/feedback/error-page/error-page.guidelines.md
Labels: documentation

#92 doc LF3.2
  applications/prisme/src/app/components/actions/buttons/buttons.feature.ts
  applications/prisme/src/app/components/actions/buttons/buttons.module.ts
  applications/prisme/src/app/components/actions/buttons/more-actions/more-actions.example.html
  applications/prisme/src/app/components/actions/buttons/more-actions/more-actions.example.ts
  applications/prisme/src/app/components/form/textfields/filter/filter.example.html
  applications/prisme/src/app/components/form/textfields/filter/filter.example.ts
  applications/prisme/src/app/components/form/textfields/palettes/palettes.example.html
  applications/prisme/src/app/components/form/textfields/palettes/palettes.example.ts
  applications/prisme/src/app/components/form/textfields/textfields.feature.ts
  applications/prisme/src/app/components/form/textfields/textfields.module.ts
  applications/prisme/src/app/components/misc/utilities/utilities.feature.html
  documentation/scss/scss-docs.ts
Labels: documentation

#94 [feat] CI
  Jenkinsfile
Labels: enhancement

#96 ci - added jenkins stage to deploy branch rc on each build
  Jenkinsfile
  applications/prisme/src/index.html
  package-lock.json
  package.json
Labels: enhancement

#97 CI au sommet
  Jenkinsfile
  applications/prisme/src/index.html
  package-lock.json
  package.json
Labels: enhancement

#118 fix images dans le markdown
  applications/prisme/src/app/app.module.ts
  libraries/common/src/lib/common.module.ts
  libraries/common/src/lib/environment/base-url.token.ts
  libraries/common/src/lib/environment/environment.module.ts
  libraries/common/src/lib/environment/index.ts
  libraries/common/src/lib/index.ts
  libraries/common/src/lib/markdown/markdown.module.ts
  libraries/common/src/lib/markdown/markdown.options.ts
Labels: bug
