Repository LuccaSA/ux-prisme, pull requests merged in 2020-10, with the labels that each got.

#404 Framed mode
  applications/prisme/src/app/components/form/formly/framed/framed.example.ts
  applications/prisme/src/app/components/form/framed/basic/basic.example.html
  applications/prisme/src/app/components/form/framed/framed.feature.html
  applications/prisme/src/app/components/form/framed/framed.feature.ts
  applications/prisme/src/app/components/form/textfields/styles/styles.example.html
  applications/prisme/src/app/components/form/textfields/styles/styles.example.ts
  applications/prisme/src/app/components/layout/filters/basic/basic.example.html
  applications/prisme/src/app/components/layout/filters/sticky/sticky.example.html
Labels: documentation

#403 Lf 5.1
  .vscode/launch.json
  applications/prisme/src/app/components/form/formly/framed/framed.example.ts
  applications/prisme/src/app/components/form/framed/basic/basic.example.html
  applications/prisme/src/app/components/form/framed/framed.feature.html
  applications/prisme/src/app/components/form/framed/framed.feature.ts
  applications/prisme/src/app/components/form/textfields/styles/styles.example.html
  applications/prisme/src/app/components/form/textfields/styles/styles.example.ts
  applications/prisme/src/app/components/layout/filters/basic/basic.example.html
  applications/prisme/src/app/components/layout/filters/sticky/sticky.example.html
  applications/prisme/src/app/components/navigation/breadcrumbs/basic/basic.example.html
  applications/prisme/src/app/home/home.component.scss
  documentation/scss/scss-docs.ts
  package-lock.json
  package.json
  tools/scss-docs.js
Labels: enhancement

#406 dependabot - enable automerge of security patch
  .dependabot/config.yaml
Labels: security

#410 added v 1.5.0 of webpacksubresource integrity
  package-lock.json
  package.json
Labels: dependencies

#412 added minimist v1.2.0
  package-lock.json
  package.json
Labels: dependencies, security
